config/routes.rb
Filmdb::Application.routes.draw do

  root 'films#index'
  resources :roleships
  resources :roles
  resources :participants
  resources :films

end

app/models/film.rb
class Film < ActiveRecord::Base
  has_many :roleships#, inverse_of: :film
  has_many :participants, through: :roleships
  has_many :roles, through: :roleships

  accepts_nested_attributes_for :roleships

  def writers=(participant)
    @writer_role = Role.find(1)
    self.roles << @writer_role
    self.participants << participant
  end

end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: [:show, :edit, :update, :destroy]
  before_action :set_joins

  # GET /films
  # GET /films.json
  def index
    @films = Film.all
  end

  # GET /films/1
  # GET /films/1.json
  def show
  end

  # GET /films/new
  def new
    @film = Film.new
    @participants.each do |p|
        @film.roleships.build(participant_id: p.id)
    end
  end

  # GET /films/1/edit
  def edit
    @participants.each do |p|
      @film.roleships.build(participant_id: p.id)
    end
  end

  # POST /films
  # POST /films.json
  def create
    @film = Film.new(film_params)

    respond_to do |format|
      if @film.save
        format.html { redirect_to @film, notice: 'Film was successfully created.' }
        format.json { render action: 'show', status: :created, location: @film }
      else
        format.html { render action: 'new' }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1
  # PATCH/PUT /films/1.json
  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to @film, notice: 'Film was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1
  # DELETE /films/1.json
  def destroy
    @film.destroy
    respond_to do |format|
      format.html { redirect_to films_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def film_params
      params.require(:film).permit(:title, :participant_ids, :role_ids, :roleships_attributes => [:is_owner, :sort_order, :participant_attributes => [:name]])
    end

    def set_joins
      @participants = Participant.all
      @roles = Role.all
    end
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/films/_form.html.haml
= form_for @film do |f|
  - if @film.errors.any?
    #error_explanation
      %h2
        = pluralize(@film.errors.count, "error")
        prohibited this film from being saved:
      %ul
        - @film.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label 'Title of the film: '
    = f.text_field :title
  -#.field
  -#  = f.label :participants
  -#  = f.select :participant_ids, options_from_collection_for_select(Participant.all, :id, :name)
  -#  = f.label :roles
  -#  = f.select :role_ids, options_from_collection_for_select(Role.all, :id, :name)
  = f.fields_for :roleships do |roleship_form|
    = participant = Participant.where(id: roleship_form.object.participant_id).first.name
    = roleship_form.check_box :participant_id
    = roleship_form.label 'Is owner?'
    = roleship_form.check_box :is_owner
    = roleship_form.label 'Sort order'
    = roleship_form.text_field :sort_order

  .actions
    = f.submit

app/views/films/edit.html.erb
<h1>Editing film</h1>

<%= render 'form' %>

<%= link_to 'Show', @film %> |
<%= link_to 'Back', films_path %>

app/views/films/index.html.erb
<h1>Listing films</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Participants</th>
      <th>Roles</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @films.each do |film| %>
      <tr>
        <td><%= film.title %></td>
        <td><%= film.participants.first.name if film.participants.first %></td>
        <td><%= film.roles.first.name if film.roles.first  %></td>
        <td><%= link_to 'Show', film %></td>
        <td><%= link_to 'Edit', edit_film_path(film) %></td>
        <td><%= link_to 'Destroy', film, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Film', new_film_path %>

app/views/films/new.html.erb
<h1>New film</h1>

<%= render 'form' %>

<%= link_to 'Back', films_path %>

app/views/films/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @film.title %>
</p>

<%= link_to 'Edit', edit_film_path(@film) %> |
<%= link_to 'Back', films_path %>