config/routes.rb
Filmdb::Application.routes.draw do

  root 'films#index'
  resources :roleships
  resources :roles
  resources :participants
  resources :films

end

app/models/roleship.rb
class Roleship < ActiveRecord::Base
  belongs_to :participant
  belongs_to :film
  belongs_to :role

  accepts_nested_attributes_for :participant

end

app/controllers/roleships_controller.rb
class RoleshipsController < ApplicationController
  before_action :set_roleship, only: [:show, :edit, :update, :destroy]

  # GET /roleships
  # GET /roleships.json
  def index
    @roleships = Roleship.all
  end

  # GET /roleships/1
  # GET /roleships/1.json
  def show
  end

  # GET /roleships/new
  def new
    @roleship = Roleship.new
  end

  # GET /roleships/1/edit
  def edit
  end

  # POST /roleships
  # POST /roleships.json
  def create
    @roleship = Roleship.new(roleship_params)

    respond_to do |format|
      if @roleship.save
        format.html { redirect_to @roleship, notice: 'Roleship was successfully created.' }
        format.json { render action: 'show', status: :created, location: @roleship }
      else
        format.html { render action: 'new' }
        format.json { render json: @roleship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roleships/1
  # PATCH/PUT /roleships/1.json
  def update
    respond_to do |format|
      if @roleship.update(roleship_params)
        format.html { redirect_to @roleship, notice: 'Roleship was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @roleship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roleships/1
  # DELETE /roleships/1.json
  def destroy
    @roleship.destroy
    respond_to do |format|
      format.html { redirect_to roleships_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_roleship
      @roleship = Roleship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def roleship_params
      params.require(:roleship).permit(:participant_id, :film_id, :role_id)
    end
end

app/helpers/roleships_helper.rb
module RoleshipsHelper
end

app/views/roleships/_form.html.erb
<%= form_for(@roleship) do |f| %>
  <% if @roleship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@roleship.errors.count, "error") %> prohibited this roleship from being saved:</h2>

      <ul>
      <% @roleship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :participant %><br>
    <%= f.text_field :participant %>
  </div>
  <div class="field">
    <%= f.label :film %><br>
    <%= f.text_field :film %>
  </div>
  <div class="field">
    <%= f.label :role %><br>
    <%= f.text_field :role %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roleships/edit.html.erb
<h1>Editing roleship</h1>

<%= render 'form' %>

<%= link_to 'Show', @roleship %> |
<%= link_to 'Back', roleships_path %>

app/views/roleships/index.html.erb
<h1>Listing roleships</h1>

<table>
  <thead>
    <tr>
      <th>Participant</th>
      <th>Film</th>
      <th>Role</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @roleships.each do |roleship| %>
      <tr>
        <td><%= roleship.participant_id %></td>
        <td><%= roleship.film_id %></td>
        <td><%= roleship.role_id %></td>
        <td><%= link_to 'Show', roleship %></td>
        <td><%= link_to 'Edit', edit_roleship_path(roleship) %></td>
        <td><%= link_to 'Destroy', roleship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Roleship', new_roleship_path %>

app/views/roleships/new.html.erb
<h1>New roleship</h1>

<%= render 'form' %>

<%= link_to 'Back', roleships_path %>

app/views/roleships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Participant:</strong>
  <%= @roleship.participant %>
</p>

<p>
  <strong>Film:</strong>
  <%= @roleship.film %>
</p>

<p>
  <strong>Role:</strong>
  <%= @roleship.role %>
</p>

<%= link_to 'Edit', edit_roleship_path(@roleship) %> |
<%= link_to 'Back', roleships_path %>